import { Button, Input, StyledButtonGroup } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Documentation from "../components/Documentation";
import styles from "../styles/Home.module.css";
import Demo from "../components/Demo";

export default function Home() {
  const handlePassword = () => {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Making the internet a safer place | CS 109 Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Demo />

      <Documentation />
    </div>
  );
}
